/*
 * @Author: VoidY
 * @Date: 2021-08-28 16:32:53
 * @LastEditTime: 2021-08-28 23:12:27
 * @LastEditors: VoidY
 * @Description:
 */
import type { NextPage } from "next";
import Link from "next/link";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          Welcome to <Link href="/bingo">Bingo</Link>
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Design by{" "}
          <span className={styles.logo}>
            <Image src="/logo.png" alt="VoidY" width={72} height={72} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
